### ISSUE TITLE
Loading the external subtitle changes the state from paused to playing

### ISSUE THREAD

**Issue by codomania** [sdroege/gst-player#54]
The issue found during external subtitle pull request still exist in master branch. Just adding it into track so that we don't forget it.  

If playback is 'paused' and then loading a new external subtitle resumes the playback. 

Steps to reproduce:
* Pause the playback
* Load new subtitle (Subtitle->new file)
This will resume the playback after loading the subtitle.

**Comment by sdroege** [comment]
I thought I fixed that with https://github.com/sdroege/gst-player/commit/9ad2e9a17b940a9e8237eb35e3693a38756a8983 and https://github.com/sdroege/gst-player/commit/5821b62ab8a7140e670521cede1f68f63f740fa8 :)

**Comment by codomania** [comment]
I tried master branch this morning and can still reproduce it. IIRC, i had similar change (i.e use target_state) during implementation and it was not working for me hence i tried app_state and that also didn't work for me. The issue happens only if playback is pause and then try loading a new external subtitle. 

if you are not able to reproduce on your side then its possible that I've have something going really weird in my setup then.

**Comment by sdroege** [comment]
I didn't try reproducing it. Can you give me a debug log?

**Comment by codomania** [comment]
https://gist.github.com/codomania/0a3e51bbe386e3ba6430

**Comment by sdroege** [comment]
This is fixed by this commit now https://github.com/sdroege/gst-player/commit/a922d085c90891b7ee9e90305d6da91e0b2127c2

Was a bug in the GTK code :)
